#!/bin/bash

# Do md5 files for all subdirectories

ver=0.1.6
me=$(basename "$0")


#### DEFAULTS

# Without the .md5 extension, which will be added automatically
md5_filename=checksums


#### FUNCTIONS

usage() {
        cat <<EOF

    Usage: $me [options] DIRECTORY

    Options:
        -f Filename : Filename for checksums (without extension. eg. "-f cs-md5". Default: $md5_filename)
        -n          : No action (dry_run). Don't actually calculate md5
        -d          : Debug (can be repeated)
        -V          : show version and exit
        -h          : This help

EOF
}

die() {
    echo "$@" 1>&2
    exit 1;
}

warn() {
    er="$@"
    echo "$er" 1>&2
    errors+=("$er")
}


confirm() {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;
            [Nn]*) echo "Aborted" ; return 1 ;;
        esac
    done
}


#### PARSE ARGUMENTS

while getopts "df:nVh" opt; do
    case $opt in
        d) (( debug+=1 ));;
        f) md5_filename=$OPTARG;;
        n) dry_run=1;;
        V) echo "$0 version $ver"; exit;;
        h) usage; exit;;
    esac
done
shift $((OPTIND -1))


if [ -z "$dir" ]; then
	usage
	die "Error: missing or wrong folder '$1'. Specify existing folder to process."
fi


#### OTHER INIT

# add .md5 to md5_filename if needed


# Check OS to select md5 command
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    md5cmd="md5sum"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    md5cmd="md5 -r"
else
    die "Error: unknown OS '$OSTYPE'. Don't know correct md5 command."
fi
(( debug )) && echo "DEBUG: md5 command set to '$md5cmd'"


#### START

start_time=$(date "+%F_%T")

(( debug )) && echo "DEBUG: dir='$dir'" >&2

# go to base directory after saving where we started
start_dir="$PWD"
cd "$dir"
# if we're in a symlink cd to the real path
if [ ! "$dir" = "$(pwd -P)" ]; then
	(( debug )) && echo "DEBUG: cd to real path '$dir'" >&2
	cd "$(pwd -P)"
fi

if [ "$PWD" = "/" ]; then
	die "Refusing to do it on system root '$PWD'"
fi


# Find all folders to process

declare -a subdirs=()
declare -a skipped=()
declare -a dcpdirs=()
declare -a wanted=()

# 1. find all non-hidden subdirectories (not if the name begins with "." like ".Trashes", ".Spotlight-V100", etc.)
#while read d; do subdirs+=("$d"); done < <(find . -type d -not -name ".*" | LC_ALL=C sort)
while IFS= read -r; do subdirs+=("$REPLY"); done < <(find . -type d -not -name ".*" | LC_ALL=C sort)

# 2. find DCP dirs to be excluded
while IFS= read -r; do dcpdirs+=("$REPLY"); done < <(find . -type f -regextype posix-extended -regex ".*/ASSETMAP(\.xml)?" -printf "%h\n" | LC_ALL=C sort)

# 3. count files and if there are any, add dir to wanted
for d in "$dir" "${subdirs[@]}"; do  # include "$dir" itself, not only it's subdirs

	(( debug )) && echo "DEBUG: cheking '$d'"

	# skip if it's a DCP
	isdcp=0
	for dcp in "${dcpdirs[@]}"; do
		if [[ "$d" =~ ^"$dcp"* ]]; then
			warn "Skipping DCP dir '$d'."
			skipped+=("$d")
			isdcp=1
			break
		fi
	done;
	(( isdcp )) && continue

	found_md5="$(find "$d" -maxdepth 1 -name "$md5_filename.md5" -print -quit)"
	if [ -n "$found_md5" ]; then
		warn "Skipping '$d'. It already has '$found_md5'"
		skipped+=("$d")
		continue
	fi

	cnt_files=$(find "$d" -maxdepth 1 -type f -not -name ".DS_Store" -not -name "._*" -not -name "*.md5" | wc -l)

	(( cnt_files )) || continue
	(( total_files += cnt_files ))

	wanted+=("$d")
done

echo "Found ${#wanted[@]} folders to process:"
printf "  * %s\n" "${wanted[@]}"

if [ "${#skipped[@]}" -gt 0 ]; then
	echo "Skipping ${#skipped[@]} folder(s) :"
	printf "  * %s\n" "${skipped[@]}"
fi

#total_size=$( du --total -sm "${wanted[@]}" 2>/dev/null | tail -1 | awk '{print $1}' ) # why did I put 2>/dev/null ?
total_size=$( du --total -sm "${wanted[@]}" | tail -1 | awk '{print $1}' )
echo "total size = $total_size MiB."

if [ "${#wanted[*]}" = 0 ]; then
	echo "Nothing to do. Aborting."
	exit 0
fi

# Do you want to start?
confirm "Start processing $total_size MiB." || { cd "$start_dir"; exit 0; }

for d in "${wanted[@]}"; do
    if [ -f "$d/$md5_filename.md5" ]; then
        echo "$d/$md5_filename.md5 file exists already. skipping"
		# ? DONE? fixme: add to list of skipped files
        continue
    fi

    echo "== Processing $d"
	(( debug )) && echo "DEBUG: PWD=$PWD, cd to $d"

    cd "$d"
    find . -maxdepth 1 -type f -not -name "$md5_filename.md5" -not -name '.DS_Store' -not -name "._*" \
    | LC_ALL=C sort \
    | while read f; do
		if (( dry_run )); then
			(( debug )) && echo "DEBUG: (-n) would do: $md5cmd \"$f\" | tee -a \"$md5_filename.md5\""
			continue
		fi
        $md5cmd "$f" | tee -a "$md5_filename.md5"
		# fixme: check exit status of md5 cmd ?!?
      done
    echo
	cd "$dir"
done


end_time=$(date "+%F_%T")

echo "Done."
echo "Started at  $start_time"
echo "Finished at $end_time"
cd "$start_dir"
